version: '3.7'
volumes:
        prometheus_data: {}
        grafana_data: {}
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:latest
    ports:
      - 9100:9100

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "1000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password #Password of Grafana
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=abc@gmail.com #Input Your Gmail
      - GF_SMTP_PASSWORD=P@ssWord123 # Input Your PassWord Of Gmail
      - GF_SMTP_SKIP_VERIFY=true
      - GF_SMTP_FROM_ADDRESS=abc@gmail.com #Input Your Gmail
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana

  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: grafana_plugin_render
    ports:
      - 8081
    environment:
      - ENABLE_METRICS= 'true'

  blackbox-exporter:
    image: prom/blackbox-exporter:master
    container_name: blackbox-exporter
    command: 
      - "--config.file=/etc/blackbox/blackbox.yml"
    volumes:
      - ./config/blackbox.yml:/etc/blackbox/blackbox.yml
    ports:
      - 9115:9115
